"""Database v0.7

Revision ID: 01a9ef897d0c
Revises: cb0f36a5d3b2
Create Date: 2023-04-30 20:14:01.705004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a9ef897d0c'
down_revision = 'cb0f36a5d3b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('game_length_sec', sa.Integer(), nullable=False),
    sa.Column('player_1_id', sa.Integer(), nullable=False),
    sa.Column('player_2_id', sa.Integer(), nullable=False),
    sa.Column('rate_change_player_1', sa.Integer(), nullable=False),
    sa.Column('rate_change_player_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['mode.id'], ),
    sa.ForeignKeyConstraint(['player_1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
