"""Database v1.1

Revision ID: 510966343696
Revises: cd1ecbf4aa90
Create Date: 2023-05-18 22:19:02.383892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510966343696'
down_revision = 'cd1ecbf4aa90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('registration_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('number_matches_blitz', sa.Integer(), nullable=False),
    sa.Column('number_matches_rapid', sa.Integer(), nullable=False),
    sa.Column('number_matches_classical', sa.Integer(), nullable=False),
    sa.Column('rate_blitz', sa.Integer(), nullable=False),
    sa.Column('rate_rapid', sa.Integer(), nullable=False),
    sa.Column('rate_classical', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
