"""Database v1.3

Revision ID: a40203a89644
Revises: 5e77d40fa33a
Create Date: 2023-05-21 12:51:07.175536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40203a89644'
down_revision = '5e77d40fa33a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('winrate_blitz', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('winrate_rapid', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('winrate_classical', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'winrate_classical')
    op.drop_column('user', 'winrate_rapid')
    op.drop_column('user', 'winrate_blitz')
    # ### end Alembic commands ###
