"""Database v0.6

Revision ID: cb0f36a5d3b2
Revises: 
Create Date: 2023-03-30 13:50:21.622585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0f36a5d3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number_matches_blitz', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('number_matches_rapid', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('number_matches_classical', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('rate_blitz', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('rate_rapid', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('rate_classical', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rate_classical')
    op.drop_column('user', 'rate_rapid')
    op.drop_column('user', 'rate_blitz')
    op.drop_column('user', 'number_matches_classical')
    op.drop_column('user', 'number_matches_rapid')
    op.drop_column('user', 'number_matches_blitz')
    # ### end Alembic commands ###
