"""Database v1.0

Revision ID: cd1ecbf4aa90
Revises: 01a9ef897d0c
Create Date: 2023-05-18 21:57:47.980720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1ecbf4aa90'
down_revision = '01a9ef897d0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
